name: 'Vue App to Github Pages'
branding:
  icon: 'activity'  
  color: 'blue'
description: 'This Action will Build your Vue Project and deploy it to Github Pages'
inputs:
  useyarn:
    description: 'Use yarn to build'
    required: false
    default: true
  cname:
    description: 'Your custom domain'
    required: false
    default: 'none'
runs:
  using: "composite"
  steps:
      - name: Build Vue
        run: |
              if [ true ==  ${{ inputs.useyarn }} ]; then yarn install --frozen-lockfile; else npm ci; fi
              if [ true ==  ${{ inputs.useyarn }} ]; then yarn build; else npm run build; fi
              if [ "none" !=  ${{ inputs.cname }} ]; then cd dist&&echo '${{ inputs.cname }}' > CNAME&&cd ..; fi
              ls
        shell: bash
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
